'use client';

import React from 'react';
import { Download, Cloud, FileCode, CheckCircle2 } from 'lucide-react';

interface ExportActionsProps {
    deviceName: string;
    lut?: number[];
}

const ExportActions: React.FC<ExportActionsProps> = ({ deviceName, lut }) => {

    const exportCube = () => {
        // Generate .cube LUT file content (Standard IRIDAS format)
        let content = `# Generated by Guardion Display Calibrator\n`;
        content += `TITLE "Calibration for ${deviceName}"\n`;
        content += `LUT_3D_SIZE 33\n\n`;

        // Mock 3D LUT data generation if not provided
        for (let i = 0; i < 33; i++) {
            const v = (i / 32).toFixed(6);
            content += `${v} ${v} ${v}\n`;
        }

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${deviceName.replace(/\s+/g, '_')}_Calibration.cube`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    const syncToCloud = () => {
        // Mock Supabase Storage upload
        alert("Profile successfully synced to Supabase Storage.");
    };

    return (
        <div className="bg-zinc-900/50 border border-white/5 rounded-2xl p-6 space-y-4">
            <div className="flex items-center gap-2 text-zinc-400 font-medium text-xs border-b border-white/5 pb-4 mb-2">
                <Download className="w-3.5 h-3.5" />
                <span>EXPORT & CLOUD SYNC</span>
            </div>

            <div className="grid grid-cols-1 gap-3">
                <button
                    onClick={exportCube}
                    className="flex items-center justify-between p-4 bg-zinc-800/80 hover:bg-zinc-800 rounded-xl transition-all border border-white/5 group"
                >
                    <div className="flex items-center gap-3">
                        <div className="p-2 bg-blue-500/10 rounded-lg text-blue-400">
                            <FileCode className="w-4 h-4" />
                        </div>
                        <div className="text-left">
                            <p className="text-xs font-bold text-zinc-100">Export .cube LUT</p>
                            <p className="text-[10px] text-zinc-500">Iridas Standard 3D LUT</p>
                        </div>
                    </div>
                    <Download className="w-4 h-4 text-zinc-700 group-hover:text-blue-500 transition-colors" />
                </button>

                <button
                    onClick={syncToCloud}
                    className="flex items-center justify-between p-4 bg-zinc-800/80 hover:bg-zinc-800 rounded-xl transition-all border border-white/5 group"
                >
                    <div className="flex items-center gap-3">
                        <div className="p-2 bg-purple-500/10 rounded-lg text-purple-400">
                            <Cloud className="w-4 h-4" />
                        </div>
                        <div className="text-left">
                            <p className="text-xs font-bold text-zinc-100">Sync to Supabase</p>
                            <p className="text-[10px] text-zinc-500">Automatic Backup & Deployment</p>
                        </div>
                    </div>
                    <div className="flex items-center gap-2">
                        <span className="text-[10px] font-bold text-zinc-600">STORED</span>
                        <CheckCircle2 className="w-4 h-4 text-green-500/50" />
                    </div>
                </button>
            </div>
        </div>
    );
};

export default ExportActions;
